/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tugas.quizmath_player.form;

import com.tugas.quizmath_player.helper.BackgroundPanel;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author syafiq
 */
public class LoadingForm extends javax.swing.JFrame {
    
     private javax.swing.JProgressBar progressBar;
      private javax.swing.JLabel logoLabel;
    /**
     * Creates new form LoadingForm
     */
     public LoadingForm() {
        initComponents(); // tetapi layoutnya akan kita replace

        setTitle("Loading...");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(500, 500);
        setLocationRelativeTo(null);

        // 🔥 Ambil gambar background
        Image bg = new ImageIcon(getClass().getResource("/images/logosekul.jpeg")).getImage();

        // 🔥 Ganti contentPane dengan BackgroundPanel agar full
        BackgroundPanel background = new BackgroundPanel(bg, true, 0);
        background.setLayout(new BorderLayout());
        setContentPane(background);

        // Tambahkan progress bar
        progressBar = new JProgressBar(0, 100);
        progressBar.setStringPainted(true);
        progressBar.setPreferredSize(new Dimension(600, 30));

        add(progressBar, BorderLayout.SOUTH);

        revalidate();
    }

    public void startLoading() {
        new Thread(() -> {
            for (int i = 0; i <= 100; i++) {
                final int value = i;
                SwingUtilities.invokeLater(() -> progressBar.setValue(value));
                
                try { Thread.sleep(50); } catch (InterruptedException ignored) {}
            }
            
            SwingUtilities.invokeLater(() -> {
                dispose();
                new LoginPicker().setVisible(true);
            });
        }).start();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
